language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: VczRdWjmFp2xNP89/pmGPx2j0pEYMzZk89ryccfhzOrqJ5W2vY2e5uojscNU6UjFyz2wyFjVKgyyEXcEOY5NteK9wBy2yhKVwnvX8mBYQCE43s4NyWAqLQVMpUFpx9GFV3dgJ0Bh1kYhBU/qyVkFcs1BuBRKS3vbrHrE5FtEzkLnS6tR+WP3rfNIlARzsEEox3GjSyy1cmF6u77LWApU9eNgyHocXYre3TAy+2YVFE/1f0nS6Np1RzsCwOmu7e0GrXU9SNy9coRYlY5TghLS4nHCI5ETp0VxxyhKPlIKerN+t+mxau7wh80O8K20pteKTUMm8svZEsJyjlHLc/U3QK/tpWenzKR11tpdKwvoORVByWygE0TN2khaWh7d+wFeIsx1VfqgX08sbuwwyIk/GmYdJn/tvh+sB/qZUuvmVt0O1GeBDpwKQYGxpqMS8SLmKVNkzF/BzE5wIHVspy1mIcLcLnZxTye+6NxAl+CX8pCsV7RLvqO3QPedU9LZ/swhGtkgzPfqg48GldIKXtuPten9JFCc/WhfiFJLodpSBGY07VMtBDlBchUt5iOg7ny8De7lFFieb2nreO0X/At0fOjg23phXQgi5ogNgHCYqdzbYARGwK1FUcBuo1+qb7mcD1s170IcAKKUzcuqPkVVsb/hA8Q+8HeA+GxGqoj3hp8=
  app: kent-noteful-v3
  on:
    repo: thinkful-ei24/kent-noteful-v3
